import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Header from "@/components/layout/Header";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Page accueil poutine</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge"></meta>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        ></link>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <div className="milieuDePage">
          <div className="centerText">
            <h2 className="accH2">
              Découvrir les <br></br> poutines
            </h2>
            <p>Trouvez la meilleur poutine!</p>
          </div>
          <div className="boutPoutEval">
            <h3 className="accH3">
              Poutines les <br></br> mieux notées
            </h3>
            <button className="boutonFleche">
              <img src="img/fleche.png" alt="fleche" id="imgFleche" />
            </button>
          </div>
        </div>
        <div className="col-3"></div>
        <div className="basDePage">
          <div id="circle">
            <img src="img/PoutineImage.png" id="poutImg" />
          </div>
        </div>
        <div className="col-4"></div>
      </main>
    </>
  );
}
